# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70a34328a941d45f6149aee66c42ee6e5b39d28b70210609ff32e106b252d04c2e889b4f02d9bb9cffcc308b054fa3a703ca1254100c698b79a3d10d99b82cbb

test:
  secret_key_base: e7331ea1d12e18bdd69dfcfe19661900ecc93bb24b87ad6de2418f20b6c3f647b9330401f88d68c2c5d6cc5c3d0a290ebc5ed48bd95c3aa8b09efd7deabf5b7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
